### Petición 1: CREAR (POST) un Plato
POST http://localhost:8080/api/platos
Content-Type: application/json

{
  "nombre": "Huevo con Jamón 4",
  "descripcion": "Delicioso desayuno de huevo y jamón",
  "precioBase": 50.00,
  "disponible": true
}

### Petición 2: CONSULTAR el Catálogo Disponible
GET http://localhost:8080/api/platos/disponibles
