### Petición 1: REGISTRAR (POST) un Nuevo Usuario

POST http://localhost:8080/api/usuarios/registro
Content-Type: application/json

{
  "nombre": "Pedro",
  "email": "pedro@gmail.com",
  "password": "123"
}